### ISSUE TITLE
 libHDFql.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by GregorDall** [mkoohafkan/hdfqlr#1]
Dear Michael,

I am trying to use hdfqlr on Ubuntu, and I am not able to get it running. 

```
> hql_load('/home/dallinger/hdfql-2.5.0/')
Error in dyn.load(dll, local = FALSE, now = TRUE) : 
  unable to load shared object '/home/dallinger/hdfql-2.5.0/wrapper/R/libHDFqlR.so':
  libHDFql.so: cannot open shared object file: No such file or directory
```

I have set environment variables as suggested in the Reference manual: 
`export LD_LIBRARY_PATH=/home/dallinger/hdfql-2.5.0/wrapper:/home/dallinger/hdfql-2.5.0/lib:$LD_LIBRARY_PATH
`

I have also tried an older version (2.2.0) but the problem persits. 

I am hoping for any suggestions. The strange thing is, that the error message is that "libHDFql.so" can not be loaded, although it shoudl "libHDFqlR.so"? Also tried loading the dll directly, since this seems to be the part that is failing, but still no luck:

```
> dyn.load("/home/dallinger/hdfql-2.5.0/wrapper/R/libHDFqlR.so", local = FALSE, now = TRUE)
Error in dyn.load("/home/dallinger/hdfql-2.5.0/wrapper/R/libHDFqlR.so",  : 
  unable to load shared object '/home/dallinger/hdfql-2.5.0/wrapper/R/libHDFqlR.so':
  libHDFql.so: cannot open shared object file: No such file or directory
```
Best Gregor

**Comment by mkoohafkan** [comment]
I don't have a Linux machine right now but I'll try to get something set up for testing. In the meantime, can you try following the instructions in the [reference manual](https://www.hdfql.com/resources/HDFqlReferenceManual.pdf) for manually connecting to HDFql?

**Comment by mkoohafkan** [comment]
There are two static library files `wrapper/R/libHDFqlR.so` and `lib/HDFql.so`, it seems to be having trouble finding the former. Can you confirm that the `LD_LIBRARY_PATH` is correct? I think you might be missing the R directory, I think it should be

```
export LD_LIBRARY_PATH=/home/dallinger/hdfql-2.5.0/wrapper/R:/home/dallinger/hdfql-2.5.0/lib:$LD_LIBRARY_PATH
```

**Comment by GregorDall** [comment]
Hi, 

I have tried your version of the export command, still no luck. I am now working with the hdf5r package, which works for me so I am happy now. 
I have extracted the library directly into my home directory, so the path should be correct. 

Best,  Gregor
